apiVersion: apps/v1
kind: Deployment
metadata:
  name: relecloud-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: relecloud-web-app
  template:
    metadata:
      labels:
        app: relecloud-web-app
    spec:
      containers:
      - name: relecloud-web-app-container
        image: acrrelazappsharedlab1025.azurecr.io/relecloud-web-app:2023.10.33
        envFrom:
        - configMapRef:
            name: web-app-config
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: relecloud-web-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: relecloud-web-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-config
data:
  AzureAd__ClientId: "649852cf-990c-490b-aa33-1943be0168c6"
  AzureAd__TenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
  App__AppConfig__Uri: "https://appcs-relaz-app-lab1025.azconfig.io"
  App__AppConfig__ManagedIdentity: "ee5f2873-8dbf-4c18-9503-06c4c1e518ab"
  App__RelecloudApi__BaseUri: "http://20.25.173.25"