# This file is part of the sample that  you can use to build your devOps automation.
# See the README markdown file for further details

trigger:
  - main

pool:
  vmImage: ubuntu-latest

container: mcr.microsoft.com/azure-dev-cli-apps:latest
variables:
      - name: env_name
        value: $(AZD_AZURE_ENV_NAME)daily
steps:

  - task: AzureCLI@2
    displayName: Azure Dev Provision
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd provision --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(env_name)
      AZURE_LOCATION: $(AZURE_LOCATION)

  - task: AzureCLI@2
    # temporary work around for known issue with multiple resource groups
    displayName: Set AZD resource group
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd env set AZURE_RESOURCE_GROUP $(env_name)-rg

  - task: AzureCLI@2
    displayName: Azure Dev Deploy
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd deploy --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(env_name)
      AZURE_LOCATION: $(AZURE_LOCATION)

  - task: AzureCLI@2
    displayName: QA - Validate Deployment
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo 'your tests here'

  - task: AzureCLI@2
    displayName: Azure Dev Down
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd down --force --purge --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(env_name)
      AZURE_LOCATION: $(AZURE_LOCATION)