apiVersion: apps/v1
kind: Deployment
metadata:
  name: relecloud-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: relecloud-web-app
  template:
    metadata:
      labels:
        app: relecloud-web-app
    spec:
      containers:
      - name: relecloud-web-app-container
        image: acrrelazappsharedlab1025.azurecr.io/relecloud-web-app:2023.10.27
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: relecloud-web-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: relecloud-web-app