# This file is part of our engineering process to build and maintain this file.
# See the README markdown file for further details

name: Add to App-Patterns project

on:
  issues:
    types: [opened, labeled]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/Azure/projects/279/
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, enhancement, needs-triage
          label-operator: OR
