# This file is part of the sample that  you can use to build your devOps automation.
# See the README markdown file for further details

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string

# on:
#   pull_request:
#     types: [opened, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_CREDENTIALS: ${{ vars.AZURE_CREDENTIALS }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_RESOURCE_GROUP: rele-${{ vars.AZURE_ENV_NAME}}-rg

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
#azd auth login --client-id "f7da2879-06c4-46c0-8fe2-28741dbc3772"  --federated-credential-provider "github"  --tenant-id "72f988bf-86f1-41af-91ab-2d7cd011db47"  
      - name: Log in with Azure (Federated Credentials)
        if: ${{ env.AZURE_CLIENT_ID != '' }}
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID" `
            --debug
        shell: pwsh

      - name: Azure Dev Provision
        run: azd provision --no-prompt

      - name: Azure Dev Deploy
        run: azd deploy --no-prompt
