# This file is part of our engineering process to build and maintain this file.
# See the README markdown file for further details

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1,13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # login to run ado commands such provision, deploy, and down	
      - name: Log in with Azure (Client Credentials)	
        if: ${{ env.AZURE_CREDENTIALS != '' }}	
        run: |	
          $info = $Env:AZURE_CREDENTIALS | ConvertFrom-Json -AsHashtable;	
          Write-Host "::add-mask::$($info.clientSecret)"	


          azd login `	      - name: Log in with Azure
            --client-id "$($info.clientId)" `	        uses: azure/login@v1
            --client-secret "$($info.clientSecret)" `	        with:
            --tenant-id "$($info.tenantId)"	          creds: ${{ secrets.AZURE_CREDENTIALS }}
        shell: pwsh	
        env:	
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Dev Down
        continue-on-error: true
        run: azd down --force --purge --no-prompt
        env:
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}daily2
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION2 }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Resource names are reserved for a period of time after deletion - ensure they're purged to keep integration running
      # https://docs.microsoft.com/en-us/azure/azure-app-configuration/faq#why-can-t-i-create-an-app-configuration-store-with-the-same-name-as-one-that-i-just-deleted
      - name: Purge App Configuration Service
        continue-on-error: true
        run: |
          chmod +x ./infra/appConfigSvcPurge.sh
          ./infra/appConfigSvcPurge.sh -g ${{ secrets.AZURE_ENV_NAME }}daily2-rg